SITENAME = "Dr Timothy Corbett-Clark"
SITEDESCRIPTION = "Personal website of Dr Timothy Corbett-Clark"
AUTHOR = "Timothy Corbett-Clark"
GITHUB_URL = "https://github.com/tcorbettclark/tcorbettclark.github.io"
COPYRIGHT_FOOTER = "Timothy Corbett-Clark, 2025"

# TODO - sort/fix
GOOGLE_ANALYTICS = "UA-6880945-2" # also the analytics.html template

MY_NAME = "Dr Timothy Corbett-Clark"
MY_SHORT_NAME = "Tim C-C"
MY_PIC = "img/me.jpg"
MY_TAGLINE = "CTO, Researcher, Architect, Developer"
